name: End to end test (Playwright)
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpeware/chromium
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
        if: runner.os == 'Linux'
      - name: Install Puppeteer
        run: yarn add puppeteer
      - name: Archive visual regression failures
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: visual-regression-report
          path: visual-regression-report/
