name: Push and Pull request
on:
  pull_request:
    branches:
      - master
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check hotfix and revert
        run: |
          if [[ ${{  toJSON(github).ref_name }} !=~ /^hotifx\s+.*$/ ]]
            echo "${{ toJSON(github) }}"
          fi
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Run test
        run: yarn test
