name: Push and Pull request
on:
  pull_request:
    branches:
      - master
  push:
jobs:
  test:
    if: ${{ !startsWith(github.ref_name, 'hotfix') && !startsWith(github.ref_name, 'Revert') && !startsWith(github.head_ref, 'Hotfix') && !startsWith(github.head_ref, 'hotfix') && !startsWith(github.head_ref, 'Revert') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install && echo '${{ startsWith(github.ref_name, 'Revert') }} and ${{ startsWith(github.ref_name, 'revert') }} ---- ${{ startsWith(github.head_ref, 'Revert') }} and ${{ startsWith(github.head_ref, 'revert') }}'
      - name: Run test
        run: yarn test && echo ${{ toJSON(github) }}
