name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: install
        run: yarn install
      - name: Run the containerized tests
        run: yarn test
      - name: Archive visual regression failures
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: visual-regression-report
          path: /home/runner/work/visual-regression-jest/visual-regression-jest/src/__image_snapshots__/__diff_output__
